#pragma once
// GENERATED by tools/gen_calendar.py - do not edit.
//
// The COMPILED-IN season floor (DATA-3). A fetched calendar always
// supersedes this; it exists so a cold boot with no network still has a
// usable season and the carousel runs offline.
//
// The season below is whatever /current/ named at BUILD time. The device
// resolves the season at RUNTIME and never assumes this one is current
// (decision 94) - a device flashed in one year follows the calendar forward
// on its own.
//
// Data: jolpi.ca, CC BY-NC-SA 4.0. This generated file is an adaptation of
// that data and carries the same licence (decision 55). The code does not.
// Built 2026-10-01 19:31 UTC
#include <cstdint>

namespace f1 {
namespace calendar {

inline constexpr uint16_t SEASON = 2026;
inline constexpr uint32_t BUILT_AT = 1790883085;  // unix, for the debug page

// Session start times are UTC unix epochs. 0 = this round does not have
// that session, or Jolpica gave a date with no time (section 3.4).
enum SessionIdx : uint8_t { FP1, FP2, FP3, SQ, SPRINT, QUALI, RACE, N_SESSIONS };

struct Round {
  uint8_t round;
  const char *name;        // raceName. NOT a source of country (decision 18)
  const char *circuit_id;  // key into f1::circuits::BY_CIRCUIT_ID
  const char *country;     // Circuit.Location.country - the flag keys on THIS
  const char *iso3;
  const char *locality;
  uint32_t start[N_SESSIONS];
};

inline constexpr Round R[23] = {
    {1, "Australian Grand Prix", "albert_park", "Australia", "AUS", "Melbourne",
     {1772760600, 1772773200, 1772847000, 0, 0, 1772859600, 1772942400}},
    {2, "Chinese Grand Prix", "shanghai", "China", "CHN", "Shanghai",
     {1773372600, 0, 0, 1773387000, 1773457200, 1773471600, 1773558000}},
    {3, "Japanese Grand Prix", "suzuka", "Japan", "JPN", "Suzuka",
     {1774578600, 1774591200, 1774665000, 0, 0, 1774677600, 1774760400}},
    {4, "Miami Grand Prix", "miami", "USA", "USA", "Miami",
     {1777651200, 0, 0, 1777667400, 1777737600, 1777752000, 1777838400}},
    {5, "Canadian Grand Prix", "villeneuve", "Canada", "CAN", "Montreal",
     {1779467400, 0, 0, 1779481800, 1779552000, 1779566400, 1779652800}},
    {6, "Monaco Grand Prix", "monaco", "Monaco", "MCO", "Monte Carlo",
     {1780659000, 1780671600, 1780741800, 0, 0, 1780754400, 1780837200}},
    {7, "Barcelona Grand Prix", "catalunya", "Spain", "ESP", "Barcelona",
     {1781263800, 1781276400, 1781346600, 0, 0, 1781359200, 1781442000}},
    {8, "Austrian Grand Prix", "red_bull_ring", "Austria", "AUT", "Spielberg",
     {1782473400, 1782486000, 1782556200, 0, 0, 1782568800, 1782651600}},
    {9, "British Grand Prix", "silverstone", "UK", "GBR", "Silverstone",
     {1783078200, 0, 0, 1783092600, 1783162800, 1783177200, 1783260000}},
    {10, "Belgian Grand Prix", "spa", "Belgium", "BEL", "Spa",
     {1784287800, 1784300400, 1784370600, 0, 0, 1784383200, 1784466000}},
    {11, "Hungarian Grand Prix", "hungaroring", "Hungary", "HUN", "Budapest",
     {1784892600, 1784905200, 1784975400, 0, 0, 1784988000, 1785070800}},
    {12, "Dutch Grand Prix", "zandvoort", "Netherlands", "NLD", "Zandvoort",
     {1787308200, 0, 0, 1787322600, 1787392800, 1787407200, 1787490000}},
    {13, "Italian Grand Prix", "monza", "Italy", "ITA", "Monza",
     {1788517800, 1788530400, 1788604200, 0, 0, 1788616800, 1788699600}},
    {14, "Spanish Grand Prix", "madring", "Spain", "ESP", "Madrid",
     {1789126200, 1789138800, 1789209000, 0, 0, 1789221600, 1789304400}},
    {15, "Azerbaijan Grand Prix", "baku", "Azerbaijan", "AZE", "Baku",
     {1790238600, 1790251200, 1790325000, 0, 0, 1790337600, 1790420400}},
    {16, "Bahrain Grand Prix in Malaysia", "sepang", "Malaysia", "MYS", "Kuala Lumpur",
     {1790915400, 1790928000, 1791001800, 0, 0, 1791014400, 1791097200}},
    {17, "Singapore Grand Prix", "marina_bay", "Singapore", "SGP", "Marina Bay",
     {1791534600, 0, 0, 1791549000, 1791622800, 1791637200, 1791720000}},
    {18, "United States Grand Prix", "americas", "USA", "USA", "Austin",
     {1792776600, 1792789200, 1792863000, 0, 0, 1792875600, 1792958400}},
    {19, "Mexico City Grand Prix", "rodriguez", "Mexico", "MEX", "Mexico City",
     {1793385000, 1793397600, 1793467800, 0, 0, 1793480400, 1793563200}},
    {20, "Brazilian Grand Prix", "interlagos", "Brazil", "BRA", "São Paulo",
     {1793979000, 1793991600, 1794061800, 0, 0, 1794074400, 1794157200}},
    {21, "Las Vegas Grand Prix", "vegas", "USA", "USA", "Las Vegas",
     {1795134600, 1795147200, 1795221000, 0, 0, 1795233600, 1795320000}},
    {22, "Qatar Grand Prix", "losail", "Qatar", "QAT", "Lusail",
     {1795786200, 1795798800, 1795876200, 0, 0, 1795888800, 1795968000}},
    {23, "Abu Dhabi Grand Prix", "yas_marina", "UAE", "ARE", "Abu Dhabi",
     {1796376600, 1796389200, 1796466600, 0, 0, 1796479200, 1796562000}},
};
inline constexpr int N_ROUNDS = 23;

}  // namespace calendar
}  // namespace f1
