#pragma once
// GENERATED by tools/gen_drivers.py - do not edit.
//
// Data: jolpi.ca, CC BY-NC-SA 4.0. This generated file is an adaptation of
// that data and carries the same licence (decision 55). The code does not.
// The 2026 entry list: drivers carrying a code, i.e. actually racing
// (DATA-10 - the season endpoint also lists reserves with no number).
// Built 2026-10-01 20:19 UTC
#include <cstdint>

namespace f1 {
namespace drivers {

struct Profile {
  const char *driver_id;   // the ONLY stable key (DATA-6)
  const char *given;
  const char *family;
  const char *code;        // 3-letter acronym, or "" - absent pre-1980s (DATA-7)
  const char *iso3;        // "" when the demonym is absent or unmapped: draw
                           // NO flag rather than a wrong one (decision 20)
  const char *dob;         // ISO date, for the age line
  uint16_t number;         // 0 when absent (DATA-7). NEVER an identity key
  uint16_t wins, starts, podiums;
  int16_t poles;           // -1 = unknown, OMIT the line (DATA-8)
  uint16_t first_season, last_season;
  uint8_t titles;
  uint8_t group;           // index into GROUP_NAME, legends only
};

inline constexpr const char *GROUP_NAME[3] = {
    "Multiple champion",
    "World champion",
    "Never champion",
};

inline constexpr Profile P[23] = {
    {"hamilton", "Lewis", "Hamilton", "HAM", "GBR", "1985-01-07", 44, 106, 395, 0, 118, 2007, 2026, 7, 0},
    {"max_verstappen", "Max", "Verstappen", "VER", "NLD", "1997-09-30", 3, 71, 248, 0, 65, 2015, 2026, 4, 0},
    {"alonso", "Fernando", "Alonso", "ALO", "ESP", "1981-07-29", 14, 32, 443, 0, 23, 2001, 2026, 2, 0},
    {"norris", "Lando", "Norris", "NOR", "GBR", "1999-11-13", 1, 13, 167, 0, 33, 2019, 2026, 1, 0},
    {"antonelli", "Andrea Kimi", "Antonelli", "ANT", "ITA", "2006-08-25", 12, 8, 41, 0, 9, 2024, 2026, 1, 0},
    {"bottas", "Valtteri", "Bottas", "BOT", "FIN", "1989-08-28", 77, 10, 262, 0, 19, 2013, 2026, 0, 0},
    {"leclerc", "Charles", "Leclerc", "LEC", "MCO", "1997-10-16", 16, 9, 188, 0, 34, 2018, 2026, 0, 0},
    {"piastri", "Oscar", "Piastri", "PIA", "AUS", "2001-04-06", 81, 9, 85, 0, 15, 2023, 2026, 0, 0},
    {"russell", "George", "Russell", "RUS", "GBR", "1998-02-15", 63, 8, 167, 0, 18, 2019, 2026, 0, 0},
    {"perez", "Sergio", "Pérez", "PER", "MEX", "1990-01-26", 11, 6, 298, 0, 4, 2011, 2026, 0, 0},
    {"sainz", "Carlos", "Sainz", "SAI", "ESP", "1994-09-01", 55, 4, 247, 0, 11, 2015, 2026, 0, 0},
    {"gasly", "Pierre", "Gasly", "GAS", "FRA", "1996-02-07", 10, 1, 193, 0, 1, 2017, 2026, 0, 0},
    {"ocon", "Esteban", "Ocon", "OCO", "FRA", "1996-09-17", 31, 1, 195, 0, 0, 2016, 2026, 0, 0},
    {"albon", "Alexander", "Albon", "ALB", "THA", "1996-03-23", 23, 0, 144, 0, 1, 2019, 2026, 0, 0},
    {"bearman", "Oliver", "Bearman", "BEA", "GBR", "2005-05-08", 87, 0, 47, 0, 0, 2024, 2026, 0, 0},
    {"bortoleto", "Gabriel", "Bortoleto", "BOR", "BRA", "2004-10-14", 5, 0, 39, 0, 0, 2025, 2026, 0, 0},
    {"colapinto", "Franco", "Colapinto", "COL", "ARG", "2003-05-27", 43, 0, 43, 0, 0, 2024, 2026, 0, 0},
    {"hadjar", "Isack", "Hadjar", "HAD", "FRA", "2004-09-28", 6, 0, 36, 0, 3, 2025, 2026, 0, 0},
    {"hulkenberg", "Nico", "Hülkenberg", "HUL", "DEU", "1987-08-19", 27, 0, 269, 0, 1, 2010, 2026, 0, 0},
    {"lawson", "Liam", "Lawson", "LAW", "NZL", "2002-02-11", 30, 0, 50, 0, 0, 2023, 2026, 0, 0},
    {"arvid_lindblad", "Arvid", "Lindblad", "LIN", "GBR", "2007-08-08", 41, 0, 18, 0, 0, 2025, 2026, 0, 0},
    {"stroll", "Lance", "Stroll", "STR", "CAN", "1998-10-29", 18, 0, 207, 0, 1, 2017, 2026, 0, 0},
    {"tsunoda", "Yuki", "Tsunoda", "TSU", "JPN", "2000-05-11", 22, 0, 117, 0, 1, 2021, 2026, 0, 0},
};
inline constexpr int N = 23;
inline constexpr uint16_t SOURCE_SEASON = 2026;

}  // namespace drivers
}  // namespace f1
