#pragma once
// GENERATED by tools/gen_facts.py - do not edit.
//
// Data: jolpi.ca, CC BY-NC-SA 4.0. This generated file is an adaptation of
// that data and carries the same licence (decision 55). The code does not.
//
// DATA-11: fastest-lap data begins in 2004, so fl_time is the fastest race
// lap SINCE 2004, not an all-time lap record. Circuits that raced before
// then have faster laps that the dataset does not carry, so the card says
// "since 2004" rather than "lap record" - the same class of honesty
// DATA-8 forces on pole counts.
// Built 2026-10-01 20:57 UTC
#include <cstdint>
#include <cstring>

namespace f1 {
namespace facts {

inline constexpr uint16_t FASTEST_LAP_FROM = 2004;

struct Fact {
  const char *circuit_id;
  uint16_t races;          // championship races held here
  const char *fl_time;     // "" when unknown
  const char *fl_who;
  uint16_t fl_year;
  const char *last_event;  // most recent winner, and what they won
  const char *last_driver;
  const char *last_team;
  uint16_t last_year;
  const char *most_wins;   // all-time most successful driver here
  uint16_t most_wins_n;
};

inline constexpr Fact F[41] = {
    {"albert_park", 29, "1:19.813", "Leclerc", 2024, "Australian Grand Prix", "Russell", "Mercedes", 2026, "Schumacher", 4},
    {"americas", 13, "1:36.169", "Leclerc", 2019, "United States Grand Prix", "Verstappen", "Red Bull", 2025, "Hamilton", 5},
    {"bahrain", 22, "55.404", "Russell", 2020, "Bahrain Grand Prix", "Piastri", "McLaren", 2025, "Hamilton", 5},
    {"baku", 10, "1:43.009", "Leclerc", 2019, "Azerbaijan Grand Prix", "Russell", "Mercedes", 2026, "Pérez", 2},
    {"catalunya", 36, "1:15.641", "Fisichella", 2005, "Barcelona Grand Prix", "Hamilton", "Ferrari", 2026, "Hamilton", 7},
    {"estoril", 13, "", "", 0, "Portuguese Grand Prix", "Villeneuve", "Williams", 1996, "Mansell", 3},
    {"galvez", 20, "", "", 0, "Argentine Grand Prix", "Schumacher", "Ferrari", 1998, "Fangio", 4},
    {"hockenheimring", 37, "1:13.780", "Räikkönen", 2004, "German Grand Prix", "Verstappen", "Red Bull", 2019, "Schumacher", 5},
    {"hungaroring", 41, "1:16.627", "Hamilton", 2020, "Hungarian Grand Prix", "Norris", "McLaren", 2026, "Hamilton", 8},
    {"imola", 32, "1:15.484", "Hamilton", 2020, "Emilia Romagna Grand Prix", "Verstappen", "Red Bull", 2025, "Schumacher", 8},
    {"indianapolis", 19, "1:10.399", "Barrichello", 2004, "United States Grand Prix", "Hamilton", "McLaren", 2007, "Schumacher", 5},
    {"interlagos", 42, "1:10.540", "Bottas", 2018, "São Paulo Grand Prix", "Norris", "McLaren", 2025, "Schumacher", 4},
    {"istanbul", 9, "1:24.770", "Pablo Montoya", 2005, "Turkish Grand Prix", "Bottas", "Mercedes", 2021, "Massa", 3},
    {"jacarepagua", 10, "", "", 0, "Brazilian Grand Prix", "Mansell", "Ferrari", 1989, "Prost", 5},
    {"jeddah", 5, "1:30.734", "Hamilton", 2021, "Saudi Arabian Grand Prix", "Piastri", "McLaren", 2025, "Verstappen", 2},
    {"kyalami", 20, "", "", 0, "South African Grand Prix", "Prost", "Williams", 1993, "Lauda", 3},
    {"las_vegas", 2, "", "", 0, "Caesars Palace Grand Prix", "Alboreto", "Tyrrell", 1982, "Alboreto", 1},
    {"losail", 4, "1:22.384", "Norris", 2024, "Qatar Grand Prix", "Verstappen", "Red Bull", 2025, "Verstappen", 3},
    {"madring", 1, "1:35.587", "Russell", 2026, "Spanish Grand Prix", "Antonelli", "Mercedes", 2026, "Antonelli", 1},
    {"magny_cours", 18, "1:15.377", "Schumacher", 2004, "French Grand Prix", "Massa", "Ferrari", 2008, "Schumacher", 9},
    {"marina_bay", 16, "1:33.808", "Hamilton", 2025, "Singapore Grand Prix", "Russell", "Mercedes", 2025, "Vettel", 5},
    {"miami", 5, "1:29.708", "Verstappen", 2023, "Miami Grand Prix", "Antonelli", "Mercedes", 2026, "Verstappen", 2},
    {"monaco", 72, "1:12.909", "Hamilton", 2021, "Monaco Grand Prix", "Antonelli", "Mercedes", 2026, "Senna", 6},
    {"monza", 76, "1:20.901", "Norris", 2025, "Italian Grand Prix", "Antonelli", "Mercedes", 2026, "Hamilton", 5},
    {"mugello", 1, "1:18.833", "Hamilton", 2020, "Tuscan Grand Prix", "Hamilton", "Mercedes", 2020, "Hamilton", 1},
    {"nurburgring", 41, "1:28.139", "Verstappen", 2020, "Eifel Grand Prix", "Hamilton", "Mercedes", 2020, "Schumacher", 6},
    {"portimao", 2, "1:18.750", "Hamilton", 2020, "Portuguese Grand Prix", "Hamilton", "Mercedes", 2021, "Hamilton", 2},
    {"red_bull_ring", 40, "1:05.619", "Sainz", 2020, "Austrian Grand Prix", "Russell", "Mercedes", 2026, "Verstappen", 5},
    {"ricard", 18, "1:32.740", "Vettel", 2019, "French Grand Prix", "Verstappen", "Red Bull", 2022, "Prost", 4},
    {"rodriguez", 25, "1:17.774", "Bottas", 2021, "Mexico City Grand Prix", "Norris", "McLaren", 2025, "Verstappen", 5},
    {"sepang", 19, "1:34.080", "Vettel", 2017, "Malaysian Grand Prix", "Verstappen", "Red Bull", 2017, "Schumacher", 4},
    {"shanghai", 19, "1:32.238", "Schumacher", 2004, "Chinese Grand Prix", "Antonelli", "Mercedes", 2026, "Hamilton", 6},
    {"silverstone", 61, "1:18.739", "Schumacher", 2004, "British Grand Prix", "Leclerc", "Ferrari", 2026, "Hamilton", 9},
    {"sochi", 8, "1:35.761", "Hamilton", 2019, "Russian Grand Prix", "Hamilton", "Mercedes", 2021, "Hamilton", 5},
    {"spa", 59, "1:44.701", "Pérez", 2024, "Belgian Grand Prix", "Antonelli", "Mercedes", 2026, "Schumacher", 6},
    {"suzuka", 36, "1:30.965", "Antonelli", 2025, "Japanese Grand Prix", "Antonelli", "Mercedes", 2026, "Schumacher", 6},
    {"vegas", 3, "1:33.365", "Verstappen", 2025, "Las Vegas Grand Prix", "Verstappen", "Red Bull", 2025, "Verstappen", 2},
    {"villeneuve", 45, "1:13.078", "Bottas", 2019, "Canadian Grand Prix", "Antonelli", "Mercedes", 2026, "Schumacher", 8},
    {"watkins_glen", 20, "", "", 0, "United States Grand Prix", "Jones", "Williams", 1980, "Clark", 3},
    {"yas_marina", 17, "1:25.637", "Magnussen", 2024, "Abu Dhabi Grand Prix", "Verstappen", "Red Bull", 2025, "Hamilton", 5},
    {"zandvoort", 36, "1:11.097", "Hamilton", 2021, "Dutch Grand Prix", "Norris", "McLaren", 2026, "Clark", 4},
};
inline constexpr int N = 41;

inline const Fact *find(const char *circuit_id) {
  if (circuit_id == nullptr || !*circuit_id) return nullptr;
  int lo = 0, hi = N - 1;
  while (lo <= hi) {
    const int mid = (lo + hi) / 2;
    const int cmp = std::strcmp(circuit_id, F[mid].circuit_id);
    if (cmp == 0) return &F[mid];
    if (cmp < 0) hi = mid - 1; else lo = mid + 1;
  }
  return nullptr;
}

}  // namespace facts
}  // namespace f1
