#!/usr/bin/env python3
"""Generate the little cars that lap the boot and About logos (f1_anim.h).

A plain top-down open-wheel silhouette - nose, front wing, wheels, sidepods, rear wing -
drawn once, pointing up, then rotated to 16 headings and stored as 8-bit alpha masks. The
device recolours each mask (LVGL image_recolor), so one set serves every car and every
colour. It is a generic silhouette: no livery, no team or series mark (decision 44).

  python3 tools/gen_cars.py        -> f1-tracker/f1_cars.h
"""
import os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "f1-tracker", "f1_cars.h")
STEPS = 16
SIZES = {"LARGE": 28, "SMALL": 18}      # the boot logo (200 px) and the About logo (112 px)
SS = 16                                # supersampling
FIT = 0.80                             # the car's length as a share of the sprite, so a diagonal one fits


def car_polys():
    """Shapes in a unit box, x -0.5..0.5 across, y 0 (nose) .. 1 (tail)."""
    P = []
    P.append([(-0.045, 0.05), (0.045, 0.05), (0.075, 0.32), (-0.075, 0.32)])                 # nose cone
    P.append([(-0.31, 0.02), (0.31, 0.02), (0.31, 0.10), (-0.31, 0.10)])                      # front wing
    P.append([(-0.11, 0.30), (0.11, 0.30), (0.145, 0.55), (0.10, 0.86), (-0.10, 0.86), (-0.145, 0.55)])  # body
    for s in (-1, 1):
        P.append([(s * 0.19, 0.19), (s * 0.31, 0.19), (s * 0.31, 0.37), (s * 0.19, 0.37)])    # front wheel
        P.append([(s * 0.185, 0.60), (s * 0.315, 0.60), (s * 0.315, 0.83), (s * 0.185, 0.83)])  # rear wheel
        P.append([(s * 0.05, 0.36), (s * 0.19, 0.28), (s * 0.19, 0.31), (s * 0.05, 0.40)])    # front axle
    P.append([(-0.26, 0.88), (0.26, 0.88), (0.26, 0.97), (-0.26, 0.97)])                      # rear wing
    return P


def sprite(n, angle):
    c = n * SS
    img = Image.new("L", (c, c), 0)
    d = ImageDraw.Draw(img)
    for poly in car_polys():
        pts = [(c / 2 + x * c * FIT, c / 2 + (y - 0.5) * c * FIT) for x, y in poly]
        d.polygon(pts, fill=255)
    img = img.rotate(-angle, resample=Image.BICUBIC, center=(c / 2, c / 2))   # clockwise from up
    return img.resize((n, n), Image.LANCZOS)


def main():
    lines = ["#pragma once",
             "// GENERATED by tools/gen_cars.py - do not edit.",
             "//",
             "// A generic top-down open-wheel silhouette at 16 headings (0 = nose up, clockwise),",
             "// as 8-bit alpha masks the device recolours. No livery, no team or series mark.",
             "#include <cstdint>", "", "namespace f1 {", "namespace cars {", "",
             f"inline constexpr int STEPS = {STEPS};"]
    for name, n in SIZES.items():
        lines.append(f"inline constexpr int SZ_{name} = {n};")
    lines.append("")
    for name, n in SIZES.items():
        lines.append(f"inline constexpr uint8_t {name}[STEPS][SZ_{name} * SZ_{name}] = {{")
        for k in range(STEPS):
            data = list(sprite(n, k * 360.0 / STEPS).getdata())
            rows = [", ".join(str(v) for v in data[i:i + n]) for i in range(0, len(data), n)]
            lines.append("    {" + ",\n     ".join(rows) + "},")
        lines.append("};")
        lines.append("")
    lines += ["}  // namespace cars", "}  // namespace f1", ""]
    open(OUT, "w").write("\n".join(lines))
    # a contact sheet to look at
    sheet = Image.new("RGB", (STEPS * 40, 100), (0x12, 0x1C, 0x33))
    for k in range(STEPS):
        for j, (name, n) in enumerate(SIZES.items()):
            s = sprite(n, k * 360.0 / STEPS)
            col = Image.new("RGB", (n, n), (0xFF, 0x8A, 0x1F))
            sheet.paste(col, (k * 40 + 8, 6 + j * 44), s)
    sheet = sheet.resize((sheet.width * 2, sheet.height * 2), Image.NEAREST)
    sheet.save("/tmp/cars-sheet.png")
    print(f"wrote {OUT} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
