#!/usr/bin/env python3
"""Generate f1-tracker/f1_flags.h - country flags as RGB565 bitmaps.

REQUIREMENTS.md 6.6, decision 34. The approach is sky-tracker's sky_flags.h:
flag-icons 4:3 SVGs rasterised and downsampled, keyed by ISO 3166-1 alpha-3.
Two sizes, matching sky-tracker so the two projects stay comparable:

  CARD 16x12  - the driver row and the detail card
  MAP  12x9   - the compact header

Differences from sky-tracker, both measured:
  * only the countries this project can actually show are generated - every
    driver demonym in gen_drivers.py plus every circuit country in
    gen_calendar.py. sky-tracker ships 79 and is missing MCO, which this
    project needs twice over (Leclerc and the Monaco GP).
  * RGB565 rather than ARGB8888: flags are opaque rectangles, so the alpha
    channel was 25% of the data carrying no information.

Source: github.com/lipis/flag-icons (MIT). Rasterised with resvg, downsampled
with a box filter (Pillow LANCZOS).

  python3 tools/gen_flags.py
"""
import argparse, datetime, io, os, sys, urllib.request
from PIL import Image
import resvg_py

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, ".cache", "flags")
RAW = "https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/{}.svg"
UA = {"User-Agent": "f1-tracker-build/1.0 (personal project)"}

CARD_W, CARD_H = 16, 12
MAP_W, MAP_H = 12, 9
SUPERSAMPLE = 8          # rasterise large, box-filter down: SVG flags have fine
                         # detail (stars, crests) that point-sampling destroys

# ISO 3166-1 alpha-3 -> alpha-2, for every country this device can show.
# Driver demonyms (gen_drivers.DEMONYM_ISO3) + circuit countries
# (gen_calendar.COUNTRY_ISO3), plus the three sky_flags.h lacks.
ISO3_ISO2 = {
    "ARE": "ae", "ARG": "ar", "AUS": "au", "AUT": "at", "AZE": "az", "BEL": "be",
    "BHR": "bh", "BRA": "br", "CAN": "ca", "CHE": "ch", "CHL": "cl", "CHN": "cn",
    "COL": "co", "CZE": "cz", "DEU": "de", "DNK": "dk", "ESP": "es", "FIN": "fi",
    "FRA": "fr", "GBR": "gb", "HUN": "hu", "IDN": "id", "IND": "in", "IRL": "ie",
    "ITA": "it", "JPN": "jp", "KOR": "kr", "LIE": "li", "MAR": "ma", "MCO": "mc",
    "MEX": "mx", "MYS": "my", "NLD": "nl", "NZL": "nz", "POL": "pl", "PRT": "pt",
    "QAT": "qa", "RUS": "ru", "SAU": "sa", "SGP": "sg", "SWE": "se", "THA": "th",
    "TUR": "tr", "URY": "uy", "USA": "us", "VEN": "ve", "ZAF": "za", "ZWE": "zw",
}


def fetch(iso2):
    os.makedirs(CACHE, exist_ok=True)
    p = os.path.join(CACHE, f"{iso2}.svg")
    if not os.path.exists(p):
        req = urllib.request.Request(RAW.format(iso2), headers=UA)
        with urllib.request.urlopen(req, timeout=40) as r:
            open(p, "wb").write(r.read())
    return open(p, "r", encoding="utf-8").read()


def raster(svg, w, h):
    png = resvg_py.svg_to_bytes(svg_string=svg, width=w * SUPERSAMPLE, height=h * SUPERSAMPLE)
    im = Image.open(io.BytesIO(bytes(png))).convert("RGB")
    return im.resize((w, h), Image.LANCZOS)


def _pixels(im):
    d = im.tobytes()
    return [(d[i], d[i + 1], d[i + 2]) for i in range(0, len(d), 3)]


def rgb565(im):
    out = []
    for (r, g, b) in im.convert("RGB").tobytes() and _pixels(im):
        out.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "f1-tracker", "f1_flags.h"))
    a = ap.parse_args()

    rows = []
    for iso3 in sorted(ISO3_ISO2):
        iso2 = ISO3_ISO2[iso3]
        try:
            svg = fetch(iso2)
        except Exception as e:
            print(f"FAIL: {iso3}/{iso2}: {e}", file=sys.stderr)
            sys.exit(1)
        card = rgb565(raster(svg, CARD_W, CARD_H))
        mp = rgb565(raster(svg, MAP_W, MAP_H))
        # A flag that rasterised to a single flat colour is almost certainly a
        # failed render, not a real flag - no national flag is monochrome.
        if len(set(card)) < 2:
            print(f"FAIL: {iso3} rasterised to one colour - bad render", file=sys.stderr)
            sys.exit(1)
        rows.append((iso3, card, mp))

    L = []; w = L.append
    w("#pragma once")
    w("// GENERATED by tools/gen_flags.py - do not edit.")
    w("//")
    w("// Flags from github.com/lipis/flag-icons (MIT), 4:3 SVGs rasterised with")
    w("// resvg and box-filtered down. RGB565, row-major, opaque.")
    w("//")
    w("// Keyed by ISO 3166-1 alpha-3. The driver flag comes from Jolpica's")
    w("// nationality demonym via gen_drivers.DEMONYM_ISO3; the circuit flag comes")
    w("// from Circuit.Location.country, NEVER the race name (decision 18).")
    w("// A driver with no resolvable nationality draws NO flag (decision 20).")
    w(f"// Built {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M UTC}")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("")
    w("namespace f1 {")
    w("namespace flags {")
    w("")
    w(f"inline constexpr int CARD_W = {CARD_W}, CARD_H = {CARD_H};")
    w(f"inline constexpr int MAP_W = {MAP_W}, MAP_H = {MAP_H};")
    w("")
    w("struct Flag {")
    w("  char iso3[4];")
    w(f"  uint16_t card[{CARD_W * CARD_H}];")
    w(f"  uint16_t map[{MAP_W * MAP_H}];")
    w("};")
    w("")
    w(f"inline constexpr Flag F[{len(rows)}] = {{")
    for iso3, card, mp in rows:
        w(f'    {{"{iso3}",')
        w("     {" + ",".join(f"0x{v:04X}" for v in card) + "},")
        w("     {" + ",".join(f"0x{v:04X}" for v in mp) + "}},")
    w("};")
    w(f"inline constexpr int N = {len(rows)};")
    w("")
    w("// Sorted by iso3, so this is a binary search. Returns nullptr for an")
    w("// unknown or empty code - the caller draws NO flag (decision 20).")
    w("inline const Flag *find(const char *iso3) {")
    w("  if (iso3 == nullptr || iso3[0] == '\\0') return nullptr;")
    w("  int lo = 0, hi = N - 1;")
    w("  while (lo <= hi) {")
    w("    const int mid = (lo + hi) / 2;")
    w("    const int cmp = std::strcmp(iso3, F[mid].iso3);")
    w("    if (cmp == 0) return &F[mid];")
    w("    if (cmp < 0) hi = mid - 1; else lo = mid + 1;")
    w("  }")
    w("  return nullptr;")
    w("}")
    w("")
    w("}  // namespace flags")
    w("}  // namespace f1")
    open(a.out, "w").write("\n".join(L) + "\n")
    per = (CARD_W * CARD_H + MAP_W * MAP_H) * 2
    print(f"{len(rows)} flags -> {a.out}")
    print(f"  {per} B each, {len(rows)*per} B total ({len(rows)*per/1024:.1f} kB)")
    print(f"  includes MCO, BHR, SAU - the three sky_flags.h lacks (6.6)")


if __name__ == "__main__":
    main()
