#!/usr/bin/env python3
"""Generate f1-tracker/f1_calendar.h - the compiled-in season floor.

REQUIREMENTS.md section 4.3 (DATA-3) and 4.2.1 (RACE-13).

The device resolves the season at RUNTIME from /current/ and a fetched calendar
always supersedes this one (decision 94). This header exists so a cold boot with
no network still has a usable season, which is what lets the carousel run
offline and makes the "no data partition" decision cost nothing (decision 6).

The season is whatever /current/ names at build time - it is NEVER pinned here.

  python3 tools/gen_calendar.py                # fetch live
  python3 tools/gen_calendar.py --offline      # from reference/samples/
"""
import argparse, json, os, sys, time, urllib.request, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "f1-tracker", "f1_calendar.h")
SAMP = os.path.join(ROOT, "reference", "samples")
BASE = "https://api.jolpi.ca/ergast/f1"
UA = {"User-Agent": "f1-tracker-build/1.0 (personal project)"}

# Jolpica's Location.country strings -> ISO 3166-1 alpha-3, for the circuit flag
# (section 6.6). This keys on the CIRCUIT's country, never the race name -
# decision 18: 2026 round 16 is served as "Bahrain Grand Prix in Malaysia".
COUNTRY_ISO3 = {
    "Australia": "AUS", "Austria": "AUT", "Azerbaijan": "AZE", "Bahrain": "BHR",
    "Belgium": "BEL", "Brazil": "BRA", "Canada": "CAN", "China": "CHN",
    "France": "FRA", "Germany": "DEU", "Hungary": "HUN", "India": "IND",
    "Italy": "ITA", "Japan": "JPN", "Korea": "KOR", "Malaysia": "MYS",
    "Mexico": "MEX", "Monaco": "MCO", "Morocco": "MAR", "Netherlands": "NLD",
    "Portugal": "PRT", "Qatar": "QAT", "Russia": "RUS", "Saudi Arabia": "SAU",
    "Singapore": "SGP", "South Africa": "ZAF", "Spain": "ESP", "Sweden": "SWE",
    "Switzerland": "CHE", "Turkey": "TUR", "UAE": "ARE", "UK": "GBR",
    "USA": "USA", "United States": "USA", "Argentina": "ARG",
}

SESSIONS = [("FirstPractice", "FP1"), ("SecondPractice", "FP2"),
            ("ThirdPractice", "FP3"), ("SprintQualifying", "SQ"),
            ("Sprint", "SPRINT"), ("Qualifying", "QUALI")]


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40) as r:
        return json.load(r)


def epoch(date, tm):
    """Jolpica serves date and time separately, both UTC with a trailing Z."""
    if not date:
        return 0
    if not tm:
        return 0            # a round with a date but no time: start is UNKNOWN,
                            # not midnight (section 3.4)
    t = f"{date}T{tm.replace('Z','')}+0000"
    return int(datetime.datetime.strptime(t, "%Y-%m-%dT%H:%M:%S%z").timestamp())


def esc(s):
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--out", default=OUT)
    a = ap.parse_args()

    if a.offline:
        d = json.load(open(os.path.join(SAMP, "jolpica-2026-races.json")))
    else:
        cur = get(f"{BASE}/current/?format=json&limit=1")["MRData"]
        season = cur["RaceTable"].get("season")
        print(f"/current/ names season {season}  ({cur['total']} rounds)")
        d = get(f"{BASE}/{season}/races/?format=json&limit=40")

    tbl = d["MRData"]["RaceTable"]
    season = tbl.get("season", "0")
    races = tbl["Races"]
    print(f"season {season}: {len(races)} rounds")

    missing_iso = sorted({r["Circuit"]["Location"]["country"] for r in races
                          if r["Circuit"]["Location"]["country"] not in COUNTRY_ISO3})
    if missing_iso:
        print(f"FAIL: no ISO3 for {missing_iso} - add to COUNTRY_ISO3", file=sys.stderr)
        sys.exit(1)

    sprint_rounds = [r["round"] for r in races if "Sprint" in r]
    print(f"sprint weekends: {sprint_rounds or 'none'}")

    L = []; w = L.append
    w("#pragma once")
    w("// GENERATED by tools/gen_calendar.py - do not edit.")
    w("//")
    w("// The COMPILED-IN season floor (DATA-3). A fetched calendar always")
    w("// supersedes this; it exists so a cold boot with no network still has a")
    w("// usable season and the carousel runs offline.")
    w("//")
    w("// The season below is whatever /current/ named at BUILD time. The device")
    w("// resolves the season at RUNTIME and never assumes this one is current")
    w("// (decision 94) - a device flashed in one year follows the calendar forward")
    w("// on its own.")
    w("//")
    w("// Data: jolpi.ca, CC BY-NC-SA 4.0. This generated file is an adaptation of")
    w("// that data and carries the same licence (decision 55). The code does not.")
    w(f"// Built {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M UTC}")
    w("#include <cstdint>")
    w("")
    w("namespace f1 {")
    w("namespace calendar {")
    w("")
    w(f"inline constexpr uint16_t SEASON = {season};")
    w(f"inline constexpr uint32_t BUILT_AT = {int(time.time())};  // unix, for the debug page")
    w("")
    w("// Session start times are UTC unix epochs. 0 = this round does not have")
    w("// that session, or Jolpica gave a date with no time (section 3.4).")
    w("enum SessionIdx : uint8_t { FP1, FP2, FP3, SQ, SPRINT, QUALI, RACE, N_SESSIONS };")
    w("")
    w("struct Round {")
    w("  uint8_t round;")
    w("  const char *name;        // raceName. NOT a source of country (decision 18)")
    w("  const char *circuit_id;  // key into f1::circuits::BY_CIRCUIT_ID")
    w("  const char *country;     // Circuit.Location.country - the flag keys on THIS")
    w("  const char *iso3;")
    w("  const char *locality;")
    w("  uint32_t start[N_SESSIONS];")
    w("};")
    w("")
    w(f"inline constexpr Round R[{len(races)}] = {{")
    for r in races:
        ci = r["Circuit"]; loc = ci["Location"]
        starts = [epoch(r.get(k, {}).get("date"), r.get(k, {}).get("time")) for k, _ in SESSIONS]
        starts.append(epoch(r.get("date"), r.get("time")))
        w(f'    {{{int(r["round"])}, "{esc(r["raceName"])}", "{esc(ci["circuitId"])}", '
          f'"{esc(loc["country"])}", "{COUNTRY_ISO3[loc["country"]]}", '
          f'"{esc(loc.get("locality"))}",')
        w(f'     {{{", ".join(str(s) for s in starts)}}}}},')
    w("};")
    w(f"inline constexpr int N_ROUNDS = {len(races)};")
    w("")
    w("}  // namespace calendar")
    w("}  // namespace f1")
    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out} ({os.path.getsize(a.out)/1024:.1f} kB source)")
    no_time = sum(1 for r in races if not r.get("time"))
    if no_time:
        print(f"note: {no_time} round(s) have a date but no time -> start = 0 (unknown)")


if __name__ == "__main__":
    main()
