#!/usr/bin/env python3
"""Generate f1-tracker/f1_facts.h - per-circuit facts beyond the GeoJSON.

REQUIREMENTS.md 5.5 (MAP-4), decision 27. Computed offline from Jolpica and
baked in, so the device never fetches them.

  * fastest race lap ever recorded at the circuit, with holder and year
  * most recent winner, with the event name and year
  * number of championship races held, and the all-time most successful driver

DATA-11, measured: Ergast-lineage FASTEST LAP data begins in 2004, the same way
qualifying data begins in 1994 (DATA-8). Monza has hosted a championship race
since 1950 but returns only 25 fastest laps. So the figure is honestly labelled
"fastest lap (since 2004)" rather than "lap record", which would be wrong for
every circuit that raced before then.

  python3 tools/gen_facts.py
"""
import argparse, datetime, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jolpica import Client

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FASTEST_LAP_DATA_FROM = 2004


def lap_seconds(t):
    m = re.match(r"(?:(\d+):)?(\d+)\.(\d+)", t or "")
    if not m:
        return None
    mins = int(m.group(1) or 0)
    return mins * 60 + int(m.group(2)) + float("0." + m.group(3))


def esc(s):
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "f1-tracker", "f1_facts.h"))
    a = ap.parse_args()

    # Only the circuitIds the device can actually resolve to a trace.
    hdr = open(os.path.join(ROOT, "f1-tracker", "f1_circuits.h")).read()
    ids = re.findall(r'\{"([a-z_0-9]+)", \d+\},\s*//', hdr)
    print(f"{len(ids)} circuitIds with a trace")

    c = Client()
    rows = []
    for cid in sorted(set(ids)):
        wins = c.get(f"circuits/{cid}/results/1/", limit=100)["MRData"]["RaceTable"]["Races"]
        fast = c.get(f"circuits/{cid}/fastest/1/results/", limit=100)["MRData"]["RaceTable"]["Races"]

        last_win = last_drv = last_team = last_event = ""
        last_year = 0
        tally = {}
        for r in wins:
            d = r["Results"][0]["Driver"]
            nm = d.get("familyName", "")
            tally[nm] = tally.get(nm, 0) + 1
        if wins:
            r = wins[-1]
            last_year = int(r["season"])
            last_event = r["raceName"]
            d = r["Results"][0]["Driver"]
            last_drv = d.get("familyName", "")
            last_team = r["Results"][0]["Constructor"]["name"]

        best = None
        for r in fast:
            fl = r["Results"][0].get("FastestLap") or {}
            t = (fl.get("Time") or {}).get("time")
            sec = lap_seconds(t)
            if sec is None:
                continue
            if best is None or sec < best[0]:
                best = (sec, t, int(r["season"]), r["Results"][0]["Driver"].get("familyName", ""))

        top, topn = "", 0
        for nm, k in tally.items():
            if k > topn or (k == topn and nm < top):
                top, topn = nm, k

        rows.append(dict(id=cid, races=len(wins),
                         fl_time=best[1] if best else "", fl_year=best[2] if best else 0,
                         fl_who=best[3] if best else "",
                         last_year=last_year, last_event=last_event,
                         last_drv=last_drv, last_team=last_team,
                         top=top, topn=topn))
        print(f"  {cid:16} races={len(wins):3}  fl={rows[-1]['fl_time'] or '-':9} "
              f"last={last_year or '-'} {last_drv or '-'}")

    print(f"\n{c.report()}")

    L = []; w = L.append
    w("#pragma once")
    w("// GENERATED by tools/gen_facts.py - do not edit.")
    w("//")
    w("// Data: jolpi.ca, CC BY-NC-SA 4.0. This generated file is an adaptation of")
    w("// that data and carries the same licence (decision 55). The code does not.")
    w("//")
    w("// DATA-11: fastest-lap data begins in 2004, so fl_time is the fastest race")
    w("// lap SINCE 2004, not an all-time lap record. Circuits that raced before")
    w("// then have faster laps that the dataset does not carry, so the card says")
    w("// \"since 2004\" rather than \"lap record\" - the same class of honesty")
    w("// DATA-8 forces on pole counts.")
    w(f"// Built {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M UTC}")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("")
    w("namespace f1 {")
    w("namespace facts {")
    w("")
    w(f"inline constexpr uint16_t FASTEST_LAP_FROM = {FASTEST_LAP_DATA_FROM};")
    w("")
    w("struct Fact {")
    w("  const char *circuit_id;")
    w("  uint16_t races;          // championship races held here")
    w("  const char *fl_time;     // \"\" when unknown")
    w("  const char *fl_who;")
    w("  uint16_t fl_year;")
    w("  const char *last_event;  // most recent winner, and what they won")
    w("  const char *last_driver;")
    w("  const char *last_team;")
    w("  uint16_t last_year;")
    w("  const char *most_wins;   // all-time most successful driver here")
    w("  uint16_t most_wins_n;")
    w("};")
    w("")
    w(f"inline constexpr Fact F[{len(rows)}] = {{")
    for r in rows:
        w(f'    {{"{esc(r["id"])}", {r["races"]}, "{esc(r["fl_time"])}", '
          f'"{esc(r["fl_who"])}", {r["fl_year"]}, "{esc(r["last_event"])}", '
          f'"{esc(r["last_drv"])}", "{esc(r["last_team"])}", {r["last_year"]}, '
          f'"{esc(r["top"])}", {r["topn"]}}},')
    w("};")
    w(f"inline constexpr int N = {len(rows)};")
    w("")
    w("inline const Fact *find(const char *circuit_id) {")
    w("  if (circuit_id == nullptr || !*circuit_id) return nullptr;")
    w("  int lo = 0, hi = N - 1;")
    w("  while (lo <= hi) {")
    w("    const int mid = (lo + hi) / 2;")
    w("    const int cmp = std::strcmp(circuit_id, F[mid].circuit_id);")
    w("    if (cmp == 0) return &F[mid];")
    w("    if (cmp < 0) hi = mid - 1; else lo = mid + 1;")
    w("  }")
    w("  return nullptr;")
    w("}")
    w("")
    w("}  // namespace facts")
    w("}  // namespace f1")
    open(a.out, "w").write("\n".join(L) + "\n")
    known = sum(1 for r in rows if r["fl_time"])
    print(f"wrote {a.out}: {len(rows)} circuits, {known} with a fastest lap")


if __name__ == "__main__":
    main()
